style"gtknotebook"{
xthickness=0
ythickness=0
GtkNotebook::tab-curvature=10
GtkNotebook::tab-overlap=1
GtkNotebook::has-backward-stepper=0
GtkNotebook::has-forward-stepper=1
GtkNotebook::has-secondary-backward-stepper=1
GtkNotebook::has-secondary-forward-stepper=0
engine"pixmap"{
image{
function=SHADOW
file="../images/gtk-2.0/none.svg"
stretch=FALSE}
image{
function=BOX_GAP
file="../images/gtk-2.0/arrow-bg.svg"
detail="notebook"
border={4,4,4,4}
stretch=TRUE}
image{
function=EXTENSION
state=ACTIVE
file="../images/gtk-2.0/tab_normal.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=EXTENSION
file="../images/gtk-2.0/tab_active.svg"
border={1,1,1,1}
stretch=TRUE
}}}class"GtkNotebook"style"gtknotebook"
