style"pathbarbutton"{
xthickness=0
ythickness=0
GtkButton::inner-border={5,5,4,4}
GtkButton::shadow-type=GTK_SHADOW_NONE
engine"pixmap"{
image{
function=BOX
shadow=OUT
file="../images/gtk-2.0/none.svg"
stretch=FALSE}
image{
function=BOX
shadow=IN
file="../images/gtk-2.0/pathbar_active.svg"
border={0,0,0,2}
stretch=TRUE}
image{
detail="buttondefault"
file="../images/gtk-2.0/none.svg"
stretch=FALSE}
image{
detail="focus"
file="../images/gtk-2.0/none.svg"
stretch=FALSE}}}
widget_class"*GtkPathBar*GtkButton"style"pathbarbutton"
widget_class"*GtkPathBar*GtkToggleButton"style"pathbarbutton"
